### ISSUE TITLE
Violating Twitter ToS

### ISSUE THREAD

**Issue by spences10** [spences10/archer-twitter-bot#7]
Remove the like functionality 👍 

https://github.com/spences10/twitter-bot-bootstrap/issues/48

**Comment by w3s7y** [comment]
I love how the only bug is violating twitter tos...

Rampage?

**Comment by spences10** [comment]
Hey @w3s7y glad you like the bot!

If you find any issues please feel free to make a PR

And remember:

![image](https://cloud.githubusercontent.com/assets/234708/26679159/c647c928-46cb-11e7-8d70-435e74edce0d.png)

Or we can quote from your blog: **"I wasn’t interested in personal gains and more on fostering a community…"**

You want to foster a community then get stuck in 👍
